// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.service.api;

import io.github.venis.hl7studio.model.Hl7ConnectorDualPortMllpReceiver;
import io.github.venis.hl7studio.service.api.Hl7ConnectorDualPortMllpReceiverService;
import io.springlets.data.domain.GlobalSearch;
import io.springlets.format.EntityResolver;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

privileged aspect Hl7ConnectorDualPortMllpReceiverService_Roo_Service {
    
    declare parents: Hl7ConnectorDualPortMllpReceiverService extends EntityResolver<Hl7ConnectorDualPortMllpReceiver, Long>;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @return Hl7ConnectorDualPortMllpReceiver
     */
    public abstract Hl7ConnectorDualPortMllpReceiver Hl7ConnectorDualPortMllpReceiverService.findOne(Long id);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorDualPortMllpReceiver
     */
    public abstract void Hl7ConnectorDualPortMllpReceiverService.delete(Hl7ConnectorDualPortMllpReceiver hl7ConnectorDualPortMllpReceiver);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entities
     * @return List
     */
    public abstract List<Hl7ConnectorDualPortMllpReceiver> Hl7ConnectorDualPortMllpReceiverService.save(Iterable<Hl7ConnectorDualPortMllpReceiver> entities);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     */
    public abstract void Hl7ConnectorDualPortMllpReceiverService.delete(Iterable<Long> ids);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entity
     * @return Hl7ConnectorDualPortMllpReceiver
     */
    public abstract Hl7ConnectorDualPortMllpReceiver Hl7ConnectorDualPortMllpReceiverService.save(Hl7ConnectorDualPortMllpReceiver entity);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @return Hl7ConnectorDualPortMllpReceiver
     */
    public abstract Hl7ConnectorDualPortMllpReceiver Hl7ConnectorDualPortMllpReceiverService.findOneForUpdate(Long id);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     * @return List
     */
    public abstract List<Hl7ConnectorDualPortMllpReceiver> Hl7ConnectorDualPortMllpReceiverService.findAll(Iterable<Long> ids);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return List
     */
    public abstract List<Hl7ConnectorDualPortMllpReceiver> Hl7ConnectorDualPortMllpReceiverService.findAll();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Long
     */
    public abstract long Hl7ConnectorDualPortMllpReceiverService.count();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public abstract Page<Hl7ConnectorDualPortMllpReceiver> Hl7ConnectorDualPortMllpReceiverService.findAll(GlobalSearch globalSearch, Pageable pageable);
    
}
