// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.service.api;

import io.github.venis.hl7studio.model.Hl7ConnectorSinglePortMllpSender;
import io.github.venis.hl7studio.service.api.Hl7ConnectorSinglePortMllpSenderService;
import io.springlets.data.domain.GlobalSearch;
import io.springlets.format.EntityResolver;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

privileged aspect Hl7ConnectorSinglePortMllpSenderService_Roo_Service {
    
    declare parents: Hl7ConnectorSinglePortMllpSenderService extends EntityResolver<Hl7ConnectorSinglePortMllpSender, Long>;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @return Hl7ConnectorSinglePortMllpSender
     */
    public abstract Hl7ConnectorSinglePortMllpSender Hl7ConnectorSinglePortMllpSenderService.findOne(Long id);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorSinglePortMllpSender
     */
    public abstract void Hl7ConnectorSinglePortMllpSenderService.delete(Hl7ConnectorSinglePortMllpSender hl7ConnectorSinglePortMllpSender);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entities
     * @return List
     */
    public abstract List<Hl7ConnectorSinglePortMllpSender> Hl7ConnectorSinglePortMllpSenderService.save(Iterable<Hl7ConnectorSinglePortMllpSender> entities);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     */
    public abstract void Hl7ConnectorSinglePortMllpSenderService.delete(Iterable<Long> ids);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entity
     * @return Hl7ConnectorSinglePortMllpSender
     */
    public abstract Hl7ConnectorSinglePortMllpSender Hl7ConnectorSinglePortMllpSenderService.save(Hl7ConnectorSinglePortMllpSender entity);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @return Hl7ConnectorSinglePortMllpSender
     */
    public abstract Hl7ConnectorSinglePortMllpSender Hl7ConnectorSinglePortMllpSenderService.findOneForUpdate(Long id);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     * @return List
     */
    public abstract List<Hl7ConnectorSinglePortMllpSender> Hl7ConnectorSinglePortMllpSenderService.findAll(Iterable<Long> ids);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return List
     */
    public abstract List<Hl7ConnectorSinglePortMllpSender> Hl7ConnectorSinglePortMllpSenderService.findAll();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Long
     */
    public abstract long Hl7ConnectorSinglePortMllpSenderService.count();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public abstract Page<Hl7ConnectorSinglePortMllpSender> Hl7ConnectorSinglePortMllpSenderService.findAll(GlobalSearch globalSearch, Pageable pageable);
    
}
