// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.service.api;

import io.github.venis.hl7studio.model.Hl7ConnectorSinglePortMllpReceiver;
import io.github.venis.hl7studio.service.api.Hl7ConnectorSinglePortMllpReceiverService;
import io.springlets.data.domain.GlobalSearch;
import io.springlets.format.EntityResolver;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

privileged aspect Hl7ConnectorSinglePortMllpReceiverService_Roo_Service {
    
    declare parents: Hl7ConnectorSinglePortMllpReceiverService extends EntityResolver<Hl7ConnectorSinglePortMllpReceiver, Long>;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @return Hl7ConnectorSinglePortMllpReceiver
     */
    public abstract Hl7ConnectorSinglePortMllpReceiver Hl7ConnectorSinglePortMllpReceiverService.findOne(Long id);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorSinglePortMllpReceiver
     */
    public abstract void Hl7ConnectorSinglePortMllpReceiverService.delete(Hl7ConnectorSinglePortMllpReceiver hl7ConnectorSinglePortMllpReceiver);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entities
     * @return List
     */
    public abstract List<Hl7ConnectorSinglePortMllpReceiver> Hl7ConnectorSinglePortMllpReceiverService.save(Iterable<Hl7ConnectorSinglePortMllpReceiver> entities);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     */
    public abstract void Hl7ConnectorSinglePortMllpReceiverService.delete(Iterable<Long> ids);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entity
     * @return Hl7ConnectorSinglePortMllpReceiver
     */
    public abstract Hl7ConnectorSinglePortMllpReceiver Hl7ConnectorSinglePortMllpReceiverService.save(Hl7ConnectorSinglePortMllpReceiver entity);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @return Hl7ConnectorSinglePortMllpReceiver
     */
    public abstract Hl7ConnectorSinglePortMllpReceiver Hl7ConnectorSinglePortMllpReceiverService.findOneForUpdate(Long id);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     * @return List
     */
    public abstract List<Hl7ConnectorSinglePortMllpReceiver> Hl7ConnectorSinglePortMllpReceiverService.findAll(Iterable<Long> ids);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return List
     */
    public abstract List<Hl7ConnectorSinglePortMllpReceiver> Hl7ConnectorSinglePortMllpReceiverService.findAll();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Long
     */
    public abstract long Hl7ConnectorSinglePortMllpReceiverService.count();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public abstract Page<Hl7ConnectorSinglePortMllpReceiver> Hl7ConnectorSinglePortMllpReceiverService.findAll(GlobalSearch globalSearch, Pageable pageable);
    
}
