addons:
  sonarqube:
    organization: "venis-github"
    token: $SONAR_TOKEN

language: java
sudo: true
install: true
jdk:
  - oraclejdk8
cache:
  directories:
  - '$HOME/.m2'
  - '$HOME/.sonar/cache'
branches:
  only:
  - master
services:
  - docker

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash mvn clean verify; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash mvn clean verify docker:build; fi'
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then bash mvn org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar; fi'

after_success: mvn
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && mvn docker:push; fi'

notifications:
  hipchat: $HIPCHAT_TOKEN@$HIPCHAT_ROOM_ID