// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.service.impl;

import io.github.venis.hl7studio.model.Hl7ConnectorSinglePortMllpReceiver;
import io.github.venis.hl7studio.repository.Hl7ConnectorSinglePortMllpReceiverRepository;
import io.github.venis.hl7studio.service.impl.Hl7ConnectorSinglePortMllpReceiverServiceImpl;
import io.springlets.data.domain.GlobalSearch;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Hl7ConnectorSinglePortMllpReceiverServiceImpl_Roo_Service_Impl {
    
    declare @type: Hl7ConnectorSinglePortMllpReceiverServiceImpl: @Service;
    
    declare @type: Hl7ConnectorSinglePortMllpReceiverServiceImpl: @Transactional(readOnly = true);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private Hl7ConnectorSinglePortMllpReceiverRepository Hl7ConnectorSinglePortMllpReceiverServiceImpl.hl7ConnectorSinglePortMllpReceiverRepository;
    
    /**
     * TODO Auto-generated constructor documentation
     * 
     * @param hl7ConnectorSinglePortMllpReceiverRepository
     */
    @Autowired
    public Hl7ConnectorSinglePortMllpReceiverServiceImpl.new(Hl7ConnectorSinglePortMllpReceiverRepository hl7ConnectorSinglePortMllpReceiverRepository) {
        setHl7ConnectorSinglePortMllpReceiverRepository(hl7ConnectorSinglePortMllpReceiverRepository);
    }

    /**
     * TODO Auto-generated method documentation
     * 
     * @return Hl7ConnectorSinglePortMllpReceiverRepository
     */
    public Hl7ConnectorSinglePortMllpReceiverRepository Hl7ConnectorSinglePortMllpReceiverServiceImpl.getHl7ConnectorSinglePortMllpReceiverRepository() {
        return hl7ConnectorSinglePortMllpReceiverRepository;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorSinglePortMllpReceiverRepository
     */
    public void Hl7ConnectorSinglePortMllpReceiverServiceImpl.setHl7ConnectorSinglePortMllpReceiverRepository(Hl7ConnectorSinglePortMllpReceiverRepository hl7ConnectorSinglePortMllpReceiverRepository) {
        this.hl7ConnectorSinglePortMllpReceiverRepository = hl7ConnectorSinglePortMllpReceiverRepository;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorSinglePortMllpReceiver
     */
    @Transactional
    public void Hl7ConnectorSinglePortMllpReceiverServiceImpl.delete(Hl7ConnectorSinglePortMllpReceiver hl7ConnectorSinglePortMllpReceiver) {
        getHl7ConnectorSinglePortMllpReceiverRepository().delete(hl7ConnectorSinglePortMllpReceiver);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entities
     * @return List
     */
    @Transactional
    public List<Hl7ConnectorSinglePortMllpReceiver> Hl7ConnectorSinglePortMllpReceiverServiceImpl.save(Iterable<Hl7ConnectorSinglePortMllpReceiver> entities) {
        return getHl7ConnectorSinglePortMllpReceiverRepository().save(entities);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     */
    @Transactional
    public void Hl7ConnectorSinglePortMllpReceiverServiceImpl.delete(Iterable<Long> ids) {
        List<Hl7ConnectorSinglePortMllpReceiver> toDelete = getHl7ConnectorSinglePortMllpReceiverRepository().findAll(ids);
        getHl7ConnectorSinglePortMllpReceiverRepository().deleteInBatch(toDelete);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entity
     * @return Hl7ConnectorSinglePortMllpReceiver
     */
    @Transactional
    public Hl7ConnectorSinglePortMllpReceiver Hl7ConnectorSinglePortMllpReceiverServiceImpl.save(Hl7ConnectorSinglePortMllpReceiver entity) {
        return getHl7ConnectorSinglePortMllpReceiverRepository().save(entity);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @return Hl7ConnectorSinglePortMllpReceiver
     */
    public Hl7ConnectorSinglePortMllpReceiver Hl7ConnectorSinglePortMllpReceiverServiceImpl.findOne(Long id) {
        return getHl7ConnectorSinglePortMllpReceiverRepository().findOne(id);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @return Hl7ConnectorSinglePortMllpReceiver
     */
    public Hl7ConnectorSinglePortMllpReceiver Hl7ConnectorSinglePortMllpReceiverServiceImpl.findOneForUpdate(Long id) {
        return getHl7ConnectorSinglePortMllpReceiverRepository().findOneDetached(id);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     * @return List
     */
    public List<Hl7ConnectorSinglePortMllpReceiver> Hl7ConnectorSinglePortMllpReceiverServiceImpl.findAll(Iterable<Long> ids) {
        return getHl7ConnectorSinglePortMllpReceiverRepository().findAll(ids);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return List
     */
    public List<Hl7ConnectorSinglePortMllpReceiver> Hl7ConnectorSinglePortMllpReceiverServiceImpl.findAll() {
        return getHl7ConnectorSinglePortMllpReceiverRepository().findAll();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Long
     */
    public long Hl7ConnectorSinglePortMllpReceiverServiceImpl.count() {
        return getHl7ConnectorSinglePortMllpReceiverRepository().count();
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public Page<Hl7ConnectorSinglePortMllpReceiver> Hl7ConnectorSinglePortMllpReceiverServiceImpl.findAll(GlobalSearch globalSearch, Pageable pageable) {
        return getHl7ConnectorSinglePortMllpReceiverRepository().findAll(globalSearch, pageable);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Class
     */
    public Class<Hl7ConnectorSinglePortMllpReceiver> Hl7ConnectorSinglePortMllpReceiverServiceImpl.getEntityType() {
        return Hl7ConnectorSinglePortMllpReceiver.class;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Class
     */
    public Class<Long> Hl7ConnectorSinglePortMllpReceiverServiceImpl.getIdType() {
        return Long.class;
    }
    
}
