// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.web;

import io.github.venis.hl7studio.service.api.Hl7ConnectorDualPortMllpReceiverService;
import io.github.venis.hl7studio.web.Hl7ConnectorDualPortMllpReceiversCollectionThymeleafController;

privileged aspect Hl7ConnectorDualPortMllpReceiversCollectionThymeleafController_Roo_Controller {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private Hl7ConnectorDualPortMllpReceiverService Hl7ConnectorDualPortMllpReceiversCollectionThymeleafController.hl7ConnectorDualPortMllpReceiverService;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Hl7ConnectorDualPortMllpReceiverService
     */
    public Hl7ConnectorDualPortMllpReceiverService Hl7ConnectorDualPortMllpReceiversCollectionThymeleafController.getHl7ConnectorDualPortMllpReceiverService() {
        return hl7ConnectorDualPortMllpReceiverService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorDualPortMllpReceiverService
     */
    public void Hl7ConnectorDualPortMllpReceiversCollectionThymeleafController.setHl7ConnectorDualPortMllpReceiverService(Hl7ConnectorDualPortMllpReceiverService hl7ConnectorDualPortMllpReceiverService) {
        this.hl7ConnectorDualPortMllpReceiverService = hl7ConnectorDualPortMllpReceiverService;
    }
    
}
