// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.web;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import io.github.venis.hl7studio.model.Hl7ConnectorDualPortMllpReceiver;
import io.github.venis.hl7studio.service.api.Hl7ConnectorDualPortMllpReceiverService;
import io.github.venis.hl7studio.web.Hl7ConnectorDualPortMllpReceiverDeserializer;
import io.springlets.web.NotFoundException;
import java.io.IOException;
import org.springframework.boot.jackson.JsonComponent;
import org.springframework.core.convert.ConversionService;

privileged aspect Hl7ConnectorDualPortMllpReceiverDeserializer_Roo_EntityDeserializer {
    
    declare @type: Hl7ConnectorDualPortMllpReceiverDeserializer: @JsonComponent;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Hl7ConnectorDualPortMllpReceiverService
     */
    public Hl7ConnectorDualPortMllpReceiverService Hl7ConnectorDualPortMllpReceiverDeserializer.getHl7ConnectorDualPortMllpReceiverService() {
        return hl7ConnectorDualPortMllpReceiverService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorDualPortMllpReceiverService
     */
    public void Hl7ConnectorDualPortMllpReceiverDeserializer.setHl7ConnectorDualPortMllpReceiverService(Hl7ConnectorDualPortMllpReceiverService hl7ConnectorDualPortMllpReceiverService) {
        this.hl7ConnectorDualPortMllpReceiverService = hl7ConnectorDualPortMllpReceiverService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ConversionService
     */
    public ConversionService Hl7ConnectorDualPortMllpReceiverDeserializer.getConversionService() {
        return conversionService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param conversionService
     */
    public void Hl7ConnectorDualPortMllpReceiverDeserializer.setConversionService(ConversionService conversionService) {
        this.conversionService = conversionService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param jsonParser
     * @param context
     * @param codec
     * @param tree
     * @return Hl7ConnectorDualPortMllpReceiver
     * @throws IOException
     */
    public Hl7ConnectorDualPortMllpReceiver Hl7ConnectorDualPortMllpReceiverDeserializer.deserializeObject(JsonParser jsonParser, DeserializationContext context, ObjectCodec codec, JsonNode tree) throws IOException {
        String idText = tree.asText();
        Long id = conversionService.convert(idText, Long.class);
        Hl7ConnectorDualPortMllpReceiver hl7ConnectorDualPortMllpReceiver = hl7ConnectorDualPortMllpReceiverService.findOne(id);
        if (hl7ConnectorDualPortMllpReceiver == null) {
            throw new NotFoundException("Hl7ConnectorDualPortMllpReceiver not found");
        }
        return hl7ConnectorDualPortMllpReceiver;
    }
    
}
