// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.web;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import io.github.venis.hl7studio.model.Hl7ConnectorSinglePortMllpSender;
import io.github.venis.hl7studio.service.api.Hl7ConnectorSinglePortMllpSenderService;
import io.github.venis.hl7studio.web.Hl7ConnectorSinglePortMllpSenderDeserializer;
import io.springlets.web.NotFoundException;
import java.io.IOException;
import org.springframework.boot.jackson.JsonComponent;
import org.springframework.core.convert.ConversionService;

privileged aspect Hl7ConnectorSinglePortMllpSenderDeserializer_Roo_EntityDeserializer {
    
    declare @type: Hl7ConnectorSinglePortMllpSenderDeserializer: @JsonComponent;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Hl7ConnectorSinglePortMllpSenderService
     */
    public Hl7ConnectorSinglePortMllpSenderService Hl7ConnectorSinglePortMllpSenderDeserializer.getHl7ConnectorSinglePortMllpSenderService() {
        return hl7ConnectorSinglePortMllpSenderService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorSinglePortMllpSenderService
     */
    public void Hl7ConnectorSinglePortMllpSenderDeserializer.setHl7ConnectorSinglePortMllpSenderService(Hl7ConnectorSinglePortMllpSenderService hl7ConnectorSinglePortMllpSenderService) {
        this.hl7ConnectorSinglePortMllpSenderService = hl7ConnectorSinglePortMllpSenderService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ConversionService
     */
    public ConversionService Hl7ConnectorSinglePortMllpSenderDeserializer.getConversionService() {
        return conversionService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param conversionService
     */
    public void Hl7ConnectorSinglePortMllpSenderDeserializer.setConversionService(ConversionService conversionService) {
        this.conversionService = conversionService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param jsonParser
     * @param context
     * @param codec
     * @param tree
     * @return Hl7ConnectorSinglePortMllpSender
     * @throws IOException
     */
    public Hl7ConnectorSinglePortMllpSender Hl7ConnectorSinglePortMllpSenderDeserializer.deserializeObject(JsonParser jsonParser, DeserializationContext context, ObjectCodec codec, JsonNode tree) throws IOException {
        String idText = tree.asText();
        Long id = conversionService.convert(idText, Long.class);
        Hl7ConnectorSinglePortMllpSender hl7ConnectorSinglePortMllpSender = hl7ConnectorSinglePortMllpSenderService.findOne(id);
        if (hl7ConnectorSinglePortMllpSender == null) {
            throw new NotFoundException("Hl7ConnectorSinglePortMllpSender not found");
        }
        return hl7ConnectorSinglePortMllpSender;
    }
    
}
