// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.web;

import io.github.venis.hl7studio.service.api.Hl7ConnectorSinglePortMllpReceiverService;
import io.github.venis.hl7studio.web.Hl7ConnectorSinglePortMllpReceiversItemThymeleafController;

privileged aspect Hl7ConnectorSinglePortMllpReceiversItemThymeleafController_Roo_Controller {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private Hl7ConnectorSinglePortMllpReceiverService Hl7ConnectorSinglePortMllpReceiversItemThymeleafController.hl7ConnectorSinglePortMllpReceiverService;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Hl7ConnectorSinglePortMllpReceiverService
     */
    public Hl7ConnectorSinglePortMllpReceiverService Hl7ConnectorSinglePortMllpReceiversItemThymeleafController.getHl7ConnectorSinglePortMllpReceiverService() {
        return hl7ConnectorSinglePortMllpReceiverService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorSinglePortMllpReceiverService
     */
    public void Hl7ConnectorSinglePortMllpReceiversItemThymeleafController.setHl7ConnectorSinglePortMllpReceiverService(Hl7ConnectorSinglePortMllpReceiverService hl7ConnectorSinglePortMllpReceiverService) {
        this.hl7ConnectorSinglePortMllpReceiverService = hl7ConnectorSinglePortMllpReceiverService;
    }
    
}
