// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.web;

import io.github.venis.hl7studio.service.api.Hl7ConnectorDualPortMllpSenderService;
import io.github.venis.hl7studio.web.Hl7ConnectorDualPortMllpSendersCollectionThymeleafController;

privileged aspect Hl7ConnectorDualPortMllpSendersCollectionThymeleafController_Roo_Controller {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private Hl7ConnectorDualPortMllpSenderService Hl7ConnectorDualPortMllpSendersCollectionThymeleafController.hl7ConnectorDualPortMllpSenderService;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Hl7ConnectorDualPortMllpSenderService
     */
    public Hl7ConnectorDualPortMllpSenderService Hl7ConnectorDualPortMllpSendersCollectionThymeleafController.getHl7ConnectorDualPortMllpSenderService() {
        return hl7ConnectorDualPortMllpSenderService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorDualPortMllpSenderService
     */
    public void Hl7ConnectorDualPortMllpSendersCollectionThymeleafController.setHl7ConnectorDualPortMllpSenderService(Hl7ConnectorDualPortMllpSenderService hl7ConnectorDualPortMllpSenderService) {
        this.hl7ConnectorDualPortMllpSenderService = hl7ConnectorDualPortMllpSenderService;
    }
    
}
