// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.web;

import io.github.venis.hl7studio.model.Hl7ConnectorCharset;
import io.github.venis.hl7studio.model.Hl7ConnectorSinglePortMllpSender;
import io.github.venis.hl7studio.model.Hl7ConnectorState;
import io.github.venis.hl7studio.model.Hl7MessageEncoding;
import io.github.venis.hl7studio.service.api.Hl7ConnectorSinglePortMllpSenderService;
import io.github.venis.hl7studio.web.Hl7ConnectorSinglePortMllpSendersItemThymeleafController;
import io.github.venis.hl7studio.web.Hl7ConnectorSinglePortMllpSendersItemThymeleafLinkFactory;
import io.springlets.web.NotFoundException;
import io.springlets.web.mvc.util.ControllerMethodLinkBuilderFactory;
import io.springlets.web.mvc.util.MethodLinkBuilderFactory;
import java.util.Arrays;
import java.util.Locale;
import javax.validation.Valid;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.util.UriComponents;

privileged aspect Hl7ConnectorSinglePortMllpSendersItemThymeleafController_Roo_Thymeleaf {
    
    declare @type: Hl7ConnectorSinglePortMllpSendersItemThymeleafController: @Controller;
    
    declare @type: Hl7ConnectorSinglePortMllpSendersItemThymeleafController: @RequestMapping(value = "/hl7connectorsingleportmllpsenders/{hl7ConnectorSinglePortMllpSender}", name = "Hl7ConnectorSinglePortMllpSendersItemThymeleafController", produces = MediaType.TEXT_HTML_VALUE);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private MessageSource Hl7ConnectorSinglePortMllpSendersItemThymeleafController.messageSource;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private MethodLinkBuilderFactory<Hl7ConnectorSinglePortMllpSendersItemThymeleafController> Hl7ConnectorSinglePortMllpSendersItemThymeleafController.itemLink;
    
    /**
     * TODO Auto-generated constructor documentation
     * 
     * @param hl7ConnectorSinglePortMllpSenderService
     * @param messageSource
     * @param linkBuilder
     */
    @Autowired
    public Hl7ConnectorSinglePortMllpSendersItemThymeleafController.new(Hl7ConnectorSinglePortMllpSenderService hl7ConnectorSinglePortMllpSenderService, MessageSource messageSource, ControllerMethodLinkBuilderFactory linkBuilder) {
        setHl7ConnectorSinglePortMllpSenderService(hl7ConnectorSinglePortMllpSenderService);
        setMessageSource(messageSource);
        setItemLink(linkBuilder.of(Hl7ConnectorSinglePortMllpSendersItemThymeleafController.class));
    }

    /**
     * TODO Auto-generated method documentation
     * 
     * @return MessageSource
     */
    public MessageSource Hl7ConnectorSinglePortMllpSendersItemThymeleafController.getMessageSource() {
        return messageSource;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param messageSource
     */
    public void Hl7ConnectorSinglePortMllpSendersItemThymeleafController.setMessageSource(MessageSource messageSource) {
        this.messageSource = messageSource;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MethodLinkBuilderFactory
     */
    public MethodLinkBuilderFactory<Hl7ConnectorSinglePortMllpSendersItemThymeleafController> Hl7ConnectorSinglePortMllpSendersItemThymeleafController.getItemLink() {
        return itemLink;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param itemLink
     */
    public void Hl7ConnectorSinglePortMllpSendersItemThymeleafController.setItemLink(MethodLinkBuilderFactory<Hl7ConnectorSinglePortMllpSendersItemThymeleafController> itemLink) {
        this.itemLink = itemLink;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @param locale
     * @param method
     * @return Hl7ConnectorSinglePortMllpSender
     */
    @ModelAttribute
    public Hl7ConnectorSinglePortMllpSender Hl7ConnectorSinglePortMllpSendersItemThymeleafController.getHl7ConnectorSinglePortMllpSender(@PathVariable("hl7ConnectorSinglePortMllpSender") Long id, Locale locale, HttpMethod method) {
        Hl7ConnectorSinglePortMllpSender hl7ConnectorSinglePortMllpSender = null;
        if (HttpMethod.PUT.equals(method)) {
            hl7ConnectorSinglePortMllpSender = hl7ConnectorSinglePortMllpSenderService.findOneForUpdate(id);
        } else {
            hl7ConnectorSinglePortMllpSender = hl7ConnectorSinglePortMllpSenderService.findOne(id);
        }
        
        if (hl7ConnectorSinglePortMllpSender == null) {
            String message = messageSource.getMessage("error_NotFound", new Object[] {"Hl7ConnectorSinglePortMllpSender", id}, "The record couldn't be found", locale);
            throw new NotFoundException(message);
        }
        return hl7ConnectorSinglePortMllpSender;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorSinglePortMllpSender
     * @param model
     * @return ModelAndView
     */
    @GetMapping(name = "show")
    public ModelAndView Hl7ConnectorSinglePortMllpSendersItemThymeleafController.show(@ModelAttribute Hl7ConnectorSinglePortMllpSender hl7ConnectorSinglePortMllpSender, Model model) {
        model.addAttribute("hl7ConnectorSinglePortMllpSender", hl7ConnectorSinglePortMllpSender);
        return new ModelAndView("hl7connectorsingleportmllpsenders/show");
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorSinglePortMllpSender
     * @param model
     * @return ModelAndView
     */
    @GetMapping(value = "/inline", name = "showInline")
    public ModelAndView Hl7ConnectorSinglePortMllpSendersItemThymeleafController.showInline(@ModelAttribute Hl7ConnectorSinglePortMllpSender hl7ConnectorSinglePortMllpSender, Model model) {
        model.addAttribute("hl7ConnectorSinglePortMllpSender", hl7ConnectorSinglePortMllpSender);
        return new ModelAndView("hl7connectorsingleportmllpsenders/showInline :: inline-content");
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param dataBinder
     */
    @InitBinder("hl7ConnectorSinglePortMllpSender")
    public void Hl7ConnectorSinglePortMllpSendersItemThymeleafController.initHl7ConnectorSinglePortMllpSenderBinder(WebDataBinder dataBinder) {
        dataBinder.setDisallowedFields("id");
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param model
     */
    public void Hl7ConnectorSinglePortMllpSendersItemThymeleafController.populateFormats(Model model) {
        model.addAttribute("application_locale", LocaleContextHolder.getLocale().getLanguage());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param model
     */
    public void Hl7ConnectorSinglePortMllpSendersItemThymeleafController.populateForm(Model model) {
        populateFormats(model);
        model.addAttribute("encoding", Arrays.asList(Hl7MessageEncoding.values()));
        model.addAttribute("charset", Arrays.asList(Hl7ConnectorCharset.values()));
        model.addAttribute("runState", Arrays.asList(Hl7ConnectorState.values()));
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorSinglePortMllpSender
     * @param model
     * @return ModelAndView
     */
    @GetMapping(value = "/edit-form", name = "editForm")
    public ModelAndView Hl7ConnectorSinglePortMllpSendersItemThymeleafController.editForm(@ModelAttribute Hl7ConnectorSinglePortMllpSender hl7ConnectorSinglePortMllpSender, Model model) {
        populateForm(model);
        
        model.addAttribute("hl7ConnectorSinglePortMllpSender", hl7ConnectorSinglePortMllpSender);
        return new ModelAndView("hl7connectorsingleportmllpsenders/edit");
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorSinglePortMllpSender
     * @param version
     * @param concurrencyControl
     * @param result
     * @param model
     * @return ModelAndView
     */
    @PutMapping(name = "update")
    public ModelAndView Hl7ConnectorSinglePortMllpSendersItemThymeleafController.update(@Valid @ModelAttribute Hl7ConnectorSinglePortMllpSender hl7ConnectorSinglePortMllpSender, @RequestParam("version") Integer version, @RequestParam(value = "concurrency", required = false, defaultValue = "") String concurrencyControl, BindingResult result, Model model) {
        // Check if provided form contain errors
        if (result.hasErrors()) {
            populateForm(model);
            
            return new ModelAndView("hl7connectorsingleportmllpsenders/edit");
        }
        // Concurrency control
        Hl7ConnectorSinglePortMllpSender existingHl7ConnectorSinglePortMllpSender = getHl7ConnectorSinglePortMllpSenderService().findOne(hl7ConnectorSinglePortMllpSender.getId());
        if(hl7ConnectorSinglePortMllpSender.getVersion() != existingHl7ConnectorSinglePortMllpSender.getVersion() && StringUtils.isEmpty(concurrencyControl)){
            populateForm(model);
            model.addAttribute("hl7ConnectorSinglePortMllpSender", hl7ConnectorSinglePortMllpSender);
            model.addAttribute("concurrency", true);
            return new ModelAndView("hl7connectorsingleportmllpsenders/edit");
        } else if(hl7ConnectorSinglePortMllpSender.getVersion() != existingHl7ConnectorSinglePortMllpSender.getVersion() && "discard".equals(concurrencyControl)){
            populateForm(model);
            model.addAttribute("hl7ConnectorSinglePortMllpSender", existingHl7ConnectorSinglePortMllpSender);
            model.addAttribute("concurrency", false);
            return new ModelAndView("hl7connectorsingleportmllpsenders/edit");
        } else if(hl7ConnectorSinglePortMllpSender.getVersion() != existingHl7ConnectorSinglePortMllpSender.getVersion() && "apply".equals(concurrencyControl)){
            // Update the version field to be able to override the existing values
            hl7ConnectorSinglePortMllpSender.setVersion(existingHl7ConnectorSinglePortMllpSender.getVersion());
        }
        Hl7ConnectorSinglePortMllpSender savedHl7ConnectorSinglePortMllpSender = getHl7ConnectorSinglePortMllpSenderService().save(hl7ConnectorSinglePortMllpSender);
        UriComponents showURI = getItemLink().to(Hl7ConnectorSinglePortMllpSendersItemThymeleafLinkFactory.SHOW).with("hl7ConnectorSinglePortMllpSender", savedHl7ConnectorSinglePortMllpSender.getId()).toUri();
        return new ModelAndView("redirect:" + showURI.toUriString());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorSinglePortMllpSender
     * @return ResponseEntity
     */
    @ResponseBody
    @DeleteMapping(name = "delete")
    public ResponseEntity<?> Hl7ConnectorSinglePortMllpSendersItemThymeleafController.delete(@ModelAttribute Hl7ConnectorSinglePortMllpSender hl7ConnectorSinglePortMllpSender) {
        getHl7ConnectorSinglePortMllpSenderService().delete(hl7ConnectorSinglePortMllpSender);
        return ResponseEntity.ok().build();
    }
    
}
