// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.web;

import io.github.venis.hl7studio.service.api.Hl7ConnectorSinglePortMllpSenderService;
import io.github.venis.hl7studio.web.Hl7ConnectorSinglePortMllpSendersItemThymeleafController;

privileged aspect Hl7ConnectorSinglePortMllpSendersItemThymeleafController_Roo_Controller {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private Hl7ConnectorSinglePortMllpSenderService Hl7ConnectorSinglePortMllpSendersItemThymeleafController.hl7ConnectorSinglePortMllpSenderService;
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Hl7ConnectorSinglePortMllpSenderService
     */
    public Hl7ConnectorSinglePortMllpSenderService Hl7ConnectorSinglePortMllpSendersItemThymeleafController.getHl7ConnectorSinglePortMllpSenderService() {
        return hl7ConnectorSinglePortMllpSenderService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param hl7ConnectorSinglePortMllpSenderService
     */
    public void Hl7ConnectorSinglePortMllpSendersItemThymeleafController.setHl7ConnectorSinglePortMllpSenderService(Hl7ConnectorSinglePortMllpSenderService hl7ConnectorSinglePortMllpSenderService) {
        this.hl7ConnectorSinglePortMllpSenderService = hl7ConnectorSinglePortMllpSenderService;
    }
    
}
