// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.repository;

import io.github.venis.hl7studio.model.Hl7ConnectorSinglePortMllpSender;
import io.github.venis.hl7studio.repository.Hl7ConnectorSinglePortMllpSenderRepository;
import io.github.venis.hl7studio.repository.Hl7ConnectorSinglePortMllpSenderRepositoryCustom;
import io.springlets.data.jpa.repository.DetachableJpaRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Hl7ConnectorSinglePortMllpSenderRepository_Roo_Jpa_Repository {
    
    declare parents: Hl7ConnectorSinglePortMllpSenderRepository extends DetachableJpaRepository<Hl7ConnectorSinglePortMllpSender, Long>;
    
    declare parents: Hl7ConnectorSinglePortMllpSenderRepository extends Hl7ConnectorSinglePortMllpSenderRepositoryCustom;
    
    declare @type: Hl7ConnectorSinglePortMllpSenderRepository: @Transactional(readOnly = true);
    
}
