// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.repository;

import com.querydsl.core.types.Path;
import com.querydsl.jpa.JPQLQuery;
import io.github.venis.hl7studio.model.Hl7ConnectorDualPortMllpReceiver;
import io.github.venis.hl7studio.model.QHl7ConnectorDualPortMllpReceiver;
import io.github.venis.hl7studio.repository.Hl7ConnectorDualPortMllpReceiverRepositoryCustom;
import io.github.venis.hl7studio.repository.Hl7ConnectorDualPortMllpReceiverRepositoryImpl;
import io.springlets.data.domain.GlobalSearch;
import io.springlets.data.jpa.repository.support.QueryDslRepositorySupportExt.AttributeMappingBuilder;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Hl7ConnectorDualPortMllpReceiverRepositoryImpl_Roo_Jpa_Repository_Impl {
    
    declare parents: Hl7ConnectorDualPortMllpReceiverRepositoryImpl implements Hl7ConnectorDualPortMllpReceiverRepositoryCustom;
    
    declare @type: Hl7ConnectorDualPortMllpReceiverRepositoryImpl: @Transactional(readOnly = true);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String Hl7ConnectorDualPortMllpReceiverRepositoryImpl.TITLE = "title";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String Hl7ConnectorDualPortMllpReceiverRepositoryImpl.ENCODING = "encoding";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String Hl7ConnectorDualPortMllpReceiverRepositoryImpl.CHARSET = "charset";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String Hl7ConnectorDualPortMllpReceiverRepositoryImpl.HOST = "host";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String Hl7ConnectorDualPortMllpReceiverRepositoryImpl.USE_TLS_SSL = "useTlsSsl";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String Hl7ConnectorDualPortMllpReceiverRepositoryImpl.DETECT_CHARSET_FROM_MESSAGE = "detectCharsetFromMessage";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String Hl7ConnectorDualPortMllpReceiverRepositoryImpl.RUN_STATE = "runState";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String Hl7ConnectorDualPortMllpReceiverRepositoryImpl.INBOUND_PORT = "inboundPort";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String Hl7ConnectorDualPortMllpReceiverRepositoryImpl.OUTBOUND_PORT = "outboundPort";
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public Page<Hl7ConnectorDualPortMllpReceiver> Hl7ConnectorDualPortMllpReceiverRepositoryImpl.findAll(GlobalSearch globalSearch, Pageable pageable) {
        
        QHl7ConnectorDualPortMllpReceiver hl7ConnectorDualPortMllpReceiver = QHl7ConnectorDualPortMllpReceiver.hl7ConnectorDualPortMllpReceiver;
        
        JPQLQuery<Hl7ConnectorDualPortMllpReceiver> query = from(hl7ConnectorDualPortMllpReceiver);
        
        Path<?>[] paths = new Path<?>[] {hl7ConnectorDualPortMllpReceiver.title,hl7ConnectorDualPortMllpReceiver.encoding,hl7ConnectorDualPortMllpReceiver.charset,hl7ConnectorDualPortMllpReceiver.host,hl7ConnectorDualPortMllpReceiver.useTlsSsl,hl7ConnectorDualPortMllpReceiver.detectCharsetFromMessage,hl7ConnectorDualPortMllpReceiver.runState,hl7ConnectorDualPortMllpReceiver.inboundPort,hl7ConnectorDualPortMllpReceiver.outboundPort};        
        applyGlobalSearch(globalSearch, query, paths);
        
        AttributeMappingBuilder mapping = buildMapper()
			.map(TITLE, hl7ConnectorDualPortMllpReceiver.title)
			.map(ENCODING, hl7ConnectorDualPortMllpReceiver.encoding)
			.map(CHARSET, hl7ConnectorDualPortMllpReceiver.charset)
			.map(HOST, hl7ConnectorDualPortMllpReceiver.host)
			.map(USE_TLS_SSL, hl7ConnectorDualPortMllpReceiver.useTlsSsl)
			.map(DETECT_CHARSET_FROM_MESSAGE, hl7ConnectorDualPortMllpReceiver.detectCharsetFromMessage)
			.map(RUN_STATE, hl7ConnectorDualPortMllpReceiver.runState)
			.map(INBOUND_PORT, hl7ConnectorDualPortMllpReceiver.inboundPort)
			.map(OUTBOUND_PORT, hl7ConnectorDualPortMllpReceiver.outboundPort);
        
        applyPagination(pageable, query, mapping);
        applyOrderById(query);
        
        return loadPage(query, pageable, hl7ConnectorDualPortMllpReceiver);
    }
    
}
