// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.venis.hl7studio.repository;

import io.github.venis.hl7studio.model.Hl7ConnectorDualPortMllpReceiver;
import io.github.venis.hl7studio.repository.Hl7ConnectorDualPortMllpReceiverRepository;
import io.github.venis.hl7studio.repository.Hl7ConnectorDualPortMllpReceiverRepositoryCustom;
import io.springlets.data.jpa.repository.DetachableJpaRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Hl7ConnectorDualPortMllpReceiverRepository_Roo_Jpa_Repository {
    
    declare parents: Hl7ConnectorDualPortMllpReceiverRepository extends DetachableJpaRepository<Hl7ConnectorDualPortMllpReceiver, Long>;
    
    declare parents: Hl7ConnectorDualPortMllpReceiverRepository extends Hl7ConnectorDualPortMllpReceiverRepositoryCustom;
    
    declare @type: Hl7ConnectorDualPortMllpReceiverRepository: @Transactional(readOnly = true);
    
}
